### ISSUE TITLE
search for and obtain data

### ISSUE THREAD

**Issue by miaforsline** [la-tree/notebook#2]

**Comment by hdolinh** [comment]
This looks like a solid dataset to use!

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/88209419/142249312-d6ce91df-46be-476b-9054-c5ce2064f1a0.png">

**Comment by hdolinh** [comment]
This one looks promising, too!

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/88209419/142249523-d780706c-dbaf-48de-bd14-8bc5067385fe.png">
