### ISSUE TITLE
visualize tree canopy, redlining, and composite map

### ISSUE THREAD

**Issue by miaforsline** [la-tree/notebook#6]

**Comment by hdolinh** [comment]
tree canopy exploratory viz

<img width="752" alt="image" src="https://user-images.githubusercontent.com/88209419/142249721-63723fcc-b43c-4192-b3f6-79dcf43df81e.png">

**Comment by hdolinh** [comment]
redlining map

<img width="790" alt="image" src="https://user-images.githubusercontent.com/88209419/142249872-07341857-8c1e-449f-bc93-6f4b87a9d272.png">

**Comment by hdolinh** [comment]
composite map

<img width="752" alt="image" src="https://user-images.githubusercontent.com/88209419/142249928-44f986c4-4d82-494f-b699-c18b81414ebe.png">
